// src/services/data.js — B2B2H expanded sample data (20 builders)
// API endpoint reference (connect FastAPI backend via VITE_API_BASE in .env):
//   GET  /api/users               → all builders
//   GET  /api/users/:id           → single profile
//   GET  /api/hackathons          → upcoming hackathons
//   GET  /api/projects            → all projects
//   GET  /api/teams/my            → current user's team
//   GET  /api/notifications       → user notifications
//   GET  /api/recommendations     → AI matches for current user
//   POST /api/recommend-team      → { idea } → roles + builders
//   POST /api/invite              → { userId, role, message }
//   PATCH /api/me                 → update profile / status

export const STATUSES = {
  LOOKING_FOR_TEAM:    { label: 'Looking For Team',    color: 'green',  ring: '#10B981' },
  OPEN_TO_INVITES:     { label: 'Open To Invitations', color: 'yellow', ring: '#F59E0B' },
  LOOKING_FOR_MEMBERS: { label: 'Looking For Members', color: 'blue',   ring: '#06B6D4' },
  IN_TEAM:             { label: 'Already In Team',     color: 'red',    ring: '#EF4444' },
  OFFLINE:             { label: 'Offline',             color: 'gray',   ring: '#6B7280' },
}

// Extended factory — adds college, district, city, state, interests, domains
const mk = (
  id, name, seed, bg,
  uni, year, branch,
  bio, status,
  skills, verified,
  github, repos, commits, stars, wins,
  projects, location,
  achievements, social,
  // new fields
  college, district, city, state,
  interests, domains
) => ({
  id,
  name,
  username: name.toLowerCase().replace(/\s+/g, ''),
  avatar: `https://api.dicebear.com/8.x/notionists/svg?seed=${seed}`,
  university: uni,
  college: college || uni,   // college = canonical short name; falls back to university
  district,
  city,
  state,
  year,
  branch,
  bio,
  status,
  skills,
  verifiedSkills: verified,
  github,
  githubStats: { repos, commits, stars },
  hackathonsWon: wins,
  projects,
  location,
  interests:  interests || [],
  domains:    domains   || [],
  joined: '2024-06',
  social,
  achievements,
})

export const users = [
  mk(1,'Jaswant MP','JaswantMP','c0aede',
    'SKCET','2nd Year','Computer Science and Engineering',
    'Computer Science student at SKCET passionate about AI, Full Stack Development, Hackathons, and Open Source. Creator of B2B2H, an AI-powered platform that helps students build high-performing teams for innovation and hackathons.',
    'LOOKING_FOR_TEAM',
    ['React','Node.js','Python','Tailwind CSS','TypeScript'],['React','Node.js','TypeScript'],
    'jaswantmp',18,247,36,2,
    [{name:'B2B2H',desc:'AI-powered platform for student collaboration and hackathon team formation.',tech:['React','Vite','Tailwind','FastAPI'],link:'#'},
     {name:'SmartAttend',desc:'Automated attendance system using face recognition for college campuses.',tech:['Python','OpenCV','FastAPI','React'],link:'#'}],
    'Dindigul, Tamil Nadu',
    ['Hack Tamil Nadu 2025 Finalist','SKCET Tech Fest Winner 2024','Open Source Contributor'],
    {github:'jaswantmp',linkedin:'jaswantmp'},
    'SKCET','Dindigul','Dindigul','Tamil Nadu',
    ['Full-Stack Development','AI/ML','Hackathons','Open Source'],['Web','AI/ML','EdTech']),

  mk(2,'Riya Nair','Riya','ffdfbf',
    'NIT Trichy','4th Year','Data Science',
    'ML engineer with a focus on healthcare AI. Published researcher with 2 papers. Looking for teams building impactful AI products.',
    'OPEN_TO_INVITES',
    ['Python','TensorFlow','PyTorch','Scikit-learn','FastAPI','LangChain'],['Python','TensorFlow','PyTorch','FastAPI'],
    'riyanair_ds',18,527,93,5,
    [{name:'MediPredict',desc:'Disease prediction using ensemble ML models with 94% accuracy.',tech:['Python','TensorFlow','FastAPI'],link:'#'},
     {name:'ResearchBot',desc:'Academic paper summarization using RAG and LangChain.',tech:['Python','LangChain','Pinecone'],link:'#'}],
    'Trichy, India',
    ['Published 2 ML Papers (IEEE)','Smart India Hackathon Winner 2024','Google Summer of Code 2024'],
    {github:'riyanair_ds',linkedin:'riyanair'},
    'NIT Trichy','Tiruchirappalli','Tiruchirappalli','Tamil Nadu',
    ['Machine Learning','Healthcare AI','Research'],['HealthTech','AI/ML','Research']),

  mk(3,'Priya Sharma','Priya','d1d4f9',
    'IIT Bombay','2nd Year','Design + CS',
    'Product designer who codes. Obsessed with design systems and accessibility. Looking to join hackathon teams as design lead.',
    'LOOKING_FOR_TEAM',
    ['Figma','React','Tailwind CSS','UI/UX','Motion Design'],['Figma','React','Tailwind CSS'],
    'priyasharma_ux',11,189,34,2,
    [{name:'DesignOS',desc:'Open source design system for student projects — 500+ GitHub stars.',tech:['React','Tailwind','Storybook'],link:'#'}],
    'Mumbai, India',
    ['Dribbble Top Designer 2025','IIT Bombay Design Club President','Adobe GenSolve Finalist'],
    {github:'priyasharma_ux',linkedin:'priyasharma',dribbble:'priyasharma'},
    'IIT Bombay','Mumbai','Mumbai','Maharashtra',
    ['Design Systems','Accessibility','Open Source'],['Design','Frontend','Open Source']),

  mk(4,'Karan Mehta','Karan','c0aede',
    'BITS Pilani','4th Year','Computer Science',
    'Backend engineer and system design enthusiast. Currently building a pre-seed edtech startup. Loves distributed systems.',
    'LOOKING_FOR_MEMBERS',
    ['Go','Rust','Kubernetes','PostgreSQL','Redis','gRPC','Docker'],['Go','PostgreSQL','Kubernetes','Docker'],
    'karanmehta_bits',32,841,176,7,
    [{name:'ClassroomOps',desc:'Kubernetes-based classroom infra orchestration platform.',tech:['Go','Kubernetes','Helm'],link:'#'},
     {name:'QueryForge',desc:'Visual SQL query builder with AI autocomplete.',tech:['Rust','PostgreSQL','WASM'],link:'#'}],
    'Pilani, India',
    ['Startup India Recognition 2025','BITS Pilani Tech Fest Winner 3x','Codeforces Expert'],
    {github:'karanmehta_bits',linkedin:'karanmehta'},
    'BITS Pilani','Jhunjhunu','Pilani','Rajasthan',
    ['Backend Engineering','Distributed Systems','EdTech Startups'],['EdTech','Infrastructure','SaaS']),

  mk(5,'Aisha Patel','Aisha','b6e3f4',
    'VIT Vellore','3rd Year','Electronics + CS',
    'IoT and embedded systems developer. Building smart campus solutions. Open to collaborative research in edge computing.',
    'IN_TEAM',
    ['Arduino','Raspberry Pi','Python','C++','MQTT','Edge Computing'],['Python','C++'],
    'aishapatel_iot',15,234,41,1,
    [{name:'SmartCampus',desc:'IoT-based campus energy monitoring and optimization.',tech:['Arduino','Python','MQTT','Grafana'],link:'#'}],
    'Vellore, India',
    ['VIT Hack Winner 2024','IEEE Student Member','TI Innovation Challenge Finalist'],
    {},
    'VIT Vellore','Vellore','Vellore','Tamil Nadu',
    ['IoT','Embedded Systems','Smart Cities'],['IoT','Hardware','Smart Cities']),

  mk(6,'Dev Raj','Dev','ffd5dc',
    'IIIT Hyderabad','2nd Year','Computer Science',
    'Mobile-first developer. Flutter + React Native. Built 3 apps with 10k+ Play Store downloads.',
    'LOOKING_FOR_TEAM',
    ['Flutter','React Native','Dart','Firebase','Swift','Kotlin'],['Flutter','Firebase','Dart'],
    'devraj_mob',19,445,88,4,
    [{name:'CampusRide',desc:'Student carpooling app — 10k+ downloads on Play Store.',tech:['Flutter','Firebase','Google Maps'],link:'#'},
     {name:'StudySync',desc:'Real-time group study scheduler with Pomodoro integration.',tech:['React Native','Node.js','Socket.io'],link:'#'}],
    'Hyderabad, India',
    ['Flutter Google Dev Expert (Associate)','IIIT Hackfest Champion','Play Store Featured App 2025'],
    {github:'devraj_mob',linkedin:'devraj',twitter:'devraj_builds'},
    'IIIT Hyderabad','Hyderabad','Hyderabad','Telangana',
    ['Mobile Development','Cross-Platform','Consumer Apps'],['Mobile','Consumer Tech','EdTech']),

  mk(7,'Sneha Krishnamurthy','Sneha','c0aede',
    'IIT Madras','3rd Year','AI & Data Science',
    'NLP researcher working on Indian language AI. Interned at Microsoft Research. Building truly multilingual AI.',
    'OPEN_TO_INVITES',
    ['Python','Transformers','NLP','HuggingFace','RLHF','FastAPI'],['Python','Transformers','HuggingFace'],
    'snehakm_nlp',14,398,127,4,
    [{name:'BharatLLM',desc:'Multilingual LLM fine-tuned on 22 Indian languages.',tech:['Python','HuggingFace','LoRA'],link:'#'},
     {name:'IndieVoice',desc:'Voice-to-text for regional Indian languages at 96% WER.',tech:['Whisper','Python','FastAPI'],link:'#'}],
    'Chennai, India',
    ['Microsoft Research Intern 2024','ACL 2025 Paper Accepted','IIT Madras AI Club President'],
    {github:'snehakm_nlp',linkedin:'snehakm'},
    'IIT Madras','Chennai','Chennai','Tamil Nadu',
    ['NLP','Multilingual AI','Research'],['AI/ML','Research','Language Tech']),

  mk(8,'Rohan Verma','Rohan','ffdfbf',
    'Delhi Technological University','4th Year','Information Technology',
    'Blockchain developer and DeFi enthusiast. Audited 5 smart contracts. Building next-gen Web3 infra for Indian students.',
    'LOOKING_FOR_MEMBERS',
    ['Solidity','Ethers.js','Hardhat','React','The Graph','IPFS'],['Solidity','React','Hardhat'],
    'rohanverma_web3',27,503,142,6,
    [{name:'EduCred',desc:'Decentralized student credential verification on Polygon.',tech:['Solidity','Hardhat','React'],link:'#'},
     {name:'CarbonDAO',desc:'DAO for community-driven carbon credit trading.',tech:['Solidity','The Graph','IPFS'],link:'#'}],
    'Delhi, India',
    ['ETHIndia 2024 Winner','Polygon zkEVM Grant Recipient','DTU Blockchain Club Founder'],
    {github:'rohanverma_web3',linkedin:'rohanverma',twitter:'rohan_web3'},
    'DTU Delhi','New Delhi','Delhi','Delhi',
    ['Blockchain','DeFi','Web3'],['Web3','Fintech','Open Source']),

  mk(9,'Ananya Singh','Ananya','d1d4f9',
    'Jadavpur University','2nd Year','Computer Science',
    'Game developer and creative technologist. Unity + Unreal Engine. Merging AI with interactive storytelling.',
    'LOOKING_FOR_TEAM',
    ['Unity','C#','Unreal Engine','Blender','Three.js','WebGL'],['Unity','C#','Three.js'],
    'ananyasingh_dev',16,278,56,2,
    [{name:'MindScape',desc:'VR mental health therapy experience for anxiety treatment.',tech:['Unity','C#','Oculus SDK'],link:'#'},
     {name:'CodeQuest',desc:'Browser-based coding education game for high schoolers.',tech:['Three.js','React','Node.js'],link:'#'}],
    'Kolkata, India',
    ['Global Game Jam 2025 Winner','Unity Student Showcase Finalist','Jadavpur CS Topper 2024'],
    {},
    'Jadavpur University','Kolkata','Kolkata','West Bengal',
    ['Game Development','VR/AR','Creative Tech'],['Gaming','XR','EdTech']),

  mk(10,'Vikram Nair','Vikram','b6e3f4',
    'NIT Karnataka','3rd Year','Mechanical + CS',
    'Robotics + ML engineer. Built autonomous drones. Interested in applying computer vision to manufacturing.',
    'OPEN_TO_INVITES',
    ['Python','ROS','OpenCV','C++','PyTorch','Embedded Systems'],['Python','OpenCV','ROS'],
    'vikramnair_rob',13,291,67,3,
    [{name:'AutoDrone',desc:'Autonomous drone navigation using LiDAR and computer vision.',tech:['Python','ROS','OpenCV','C++'],link:'#'},
     {name:'DefectVision',desc:'Manufacturing defect detection at 99.1% accuracy.',tech:['PyTorch','FastAPI','OpenCV'],link:'#'}],
    'Surathkal, India',
    ['Robocon India 2025 Finalist','ISRO Innovation Challenge Top 20','NIT Karnataka Fest Winner'],
    {github:'vikramnair_rob',linkedin:'vikramnair'},
    'NIT Karnataka','Dakshina Kannada','Surathkal','Karnataka',
    ['Robotics','Computer Vision','Drone Tech'],['Robotics','Manufacturing','AI/ML']),

  mk(11,'Meera Iyer','Meera','ffd5dc',
    'PSG College of Technology','4th Year','Computer Science',
    'Full-stack developer specializing in SaaS products. Built 2 products with paying customers. Looking for co-builders.',
    'LOOKING_FOR_MEMBERS',
    ['Next.js','TypeScript','Prisma','PostgreSQL','Stripe','Redis'],['Next.js','TypeScript','PostgreSQL'],
    'meeraiyer_dev',22,467,89,4,
    [{name:'InvoicePad',desc:'SaaS invoicing tool — 50 paying customers, $800 MRR.',tech:['Next.js','Stripe','PostgreSQL'],link:'#'},
     {name:'FormCraft',desc:'No-code form builder for Indian SMBs.',tech:['Next.js','TypeScript','Prisma'],link:'#'}],
    'Coimbatore, India',
    ['PSG Tech Startup of the Year 2025','YC Apply Week Participant','Women in Tech India 30 Under 30'],
    {github:'meeraiyer_dev',linkedin:'meeraiyer',twitter:'meera_builds'},
    'PSG College of Technology','Coimbatore','Coimbatore','Tamil Nadu',
    ['SaaS','Full-Stack','Startups'],['SaaS','Fintech','Productivity']),

  mk(12,'Harsh Agarwal','Harsh','c0aede',
    'IIT Delhi','3rd Year','Computer Science',
    'Competitive programmer turned product engineer. Codeforces Grandmaster. Building tools that help devs ship faster.',
    'OFFLINE',
    ['C++','Java','Spring Boot','System Design','Kafka','Redis'],['C++','Java','Spring Boot'],
    'harshagarwal_cp',8,143,312,5,
    [{name:'AlgoVisual',desc:'Algorithm visualization platform with 15k monthly users.',tech:['React','D3.js','Spring Boot'],link:'#'},
     {name:'CodeCollab',desc:'Real-time collaborative coding editor with execution sandbox.',tech:['Java','Docker','Socket.io'],link:'#'}],
    'Delhi, India',
    ['Codeforces Grandmaster (Rank < 50 India)','ICPC Asia Regional 2024','IIT Delhi Best Coder 2024'],
    {github:'harshagarwal_cp',linkedin:'harshagarwal'},
    'IIT Delhi','New Delhi','Delhi','Delhi',
    ['Competitive Programming','System Design','Developer Tools'],['Developer Tools','Backend','EdTech']),

  mk(13,'Zara Khan','Zara','ffdfbf',
    'Manipal Institute of Technology','2nd Year','Computer Science',
    'Cybersecurity researcher and ethical hacker. CTF enthusiast. Building secure infra tools for fintech and security.',
    'LOOKING_FOR_TEAM',
    ['Python','Penetration Testing','Burp Suite','Rust','Cryptography','Linux'],['Python','Rust'],
    'zarakhan_sec',21,334,78,3,
    [{name:'VaultKey',desc:'Zero-knowledge proof-based password manager.',tech:['Rust','ZK-SNARKs','React'],link:'#'},
     {name:'TraceGuard',desc:'API security scanner for fast vulnerability detection.',tech:['Python','FastAPI','Docker'],link:'#'}],
    'Manipal, India',
    ['CTFtime Top 100 India 2025','Google Bug Bounty Hall of Fame','MIT Cybersecurity Mentorship'],
    {github:'zarakhan_sec',linkedin:'zarakhan'},
    'MIT Manipal','Udupi','Manipal','Karnataka',
    ['Cybersecurity','Ethical Hacking','Cryptography'],['Security','Fintech','Infrastructure']),

  mk(14,'Siddharth Rao','Siddharth','b6e3f4',
    'Amrita Vishwa Vidyapeetham','4th Year','ECE',
    'Signal processing + ML researcher. Working on brain-computer interface research. Looking for cross-disciplinary teams.',
    'OPEN_TO_INVITES',
    ['Python','MATLAB','Signal Processing','TensorFlow','EEG Analysis','C'],['Python','TensorFlow'],
    'sidrao_bci',10,198,44,2,
    [{name:'NeuroType',desc:'EEG-based typing interface for paralysis patients.',tech:['Python','MNE','TensorFlow'],link:'#'},
     {name:'SleepScore',desc:'Automated sleep stage classification from EEG signals.',tech:['Python','SciPy','Scikit-learn'],link:'#'}],
    'Coimbatore, India',
    ['IEEE EMBC 2025 Paper Accepted','Amrita BCI Lab Research Scholar','DST Research Grant 2024'],
    {github:'sidrao_bci',linkedin:'siddharthrao'},
    'Amrita Vishwa Vidyapeetham','Coimbatore','Coimbatore','Tamil Nadu',
    ['Brain-Computer Interface','Signal Processing','HealthTech'],['HealthTech','Research','AI/ML']),

  mk(15,'Pooja Desai','Pooja','d1d4f9',
    'DAIICT Gandhinagar','3rd Year','Information & Communication Technology',
    'Product manager with an engineering background. Loves user research, data, and shipping products people actually use.',
    'LOOKING_FOR_TEAM',
    ['Product Management','SQL','Python','Figma','User Research','A/B Testing'],['SQL','Python'],
    'poojadesai_pm',7,89,15,3,
    [{name:'ProductLab',desc:'Student PM community with structured case study curriculum.',tech:['React','Node.js','PostgreSQL'],link:'#'}],
    'Gandhinagar, India',
    ['PM School India Top 50 2025','DAIICT Entrepreneurship Cell Chair','Product used by 500+ students'],
    {github:'poojadesai_pm',linkedin:'poojadesai'},
    'DAIICT','Gandhinagar','Gandhinagar','Gujarat',
    ['Product Management','User Research','EdTech'],['EdTech','SaaS','Productivity']),

  mk(16,'Aryan Bhatt','AryanB','c0aede',
    'Thapar University','2nd Year','Computer Engineering',
    'DevOps engineer and cloud infrastructure builder. Automates everything. Runs production Kubernetes clusters for 3 student startups.',
    'OPEN_TO_INVITES',
    ['AWS','Kubernetes','Terraform','CI/CD','Docker','Linux','Ansible'],['AWS','Kubernetes','Docker','Terraform'],
    'aryanbhatt_devops',29,612,93,2,
    [{name:'InfraWiz',desc:'One-click K8s cluster provisioning for student projects.',tech:['Terraform','AWS','Helm'],link:'#'},
     {name:'MonitorX',desc:'Unified observability dashboard for microservices.',tech:['Prometheus','Grafana','Docker'],link:'#'}],
    'Patiala, India',
    ['AWS Certified Solutions Architect','Thapar DevOps Track Winner','CKA Certified'],
    {github:'aryanbhatt_devops',linkedin:'aryanbhatt'},
    'Thapar University','Patiala','Patiala','Punjab',
    ['DevOps','Cloud Infrastructure','Kubernetes'],['Infrastructure','SaaS','Developer Tools']),

  mk(17,'Ishaan Gupta','IshaanG','ffd5dc',
    'Pune Institute of Computer Technology','3rd Year','Computer Engineering',
    'Frontend architect with obsessive attention to performance and accessibility. Built design systems used across 10+ projects.',
    'LOOKING_FOR_TEAM',
    ['React','Vue.js','TypeScript','Vite','CSS Animation','Web Accessibility'],['React','TypeScript','Vue.js'],
    'ishaangupta_fe',33,721,204,5,
    [{name:'UIKit Pro',desc:'Accessible React component library with 80+ components.',tech:['React','TypeScript','Storybook'],link:'#'},
     {name:'AnimateX',desc:'Declarative animation library for React — 3k npm weekly.',tech:['React','Framer Motion','TypeScript'],link:'#'}],
    'Pune, India',
    ['React Summit Speaker 2025','PICT HackGenZ Winner','npm package 3k weekly downloads'],
    {github:'ishaangupta_fe',linkedin:'ishaangupta',twitter:'ishaan_fe'},
    'PICT Pune','Pune','Pune','Maharashtra',
    ['Frontend Engineering','Design Systems','Web Performance'],['Frontend','Design','Open Source']),

  mk(18,'Tanya Mishra','Tanya','b6e3f4',
    'IIIT Bangalore','1st Year (PG)','Human-Computer Interaction',
    'UX researcher with a CS background. Runs usability studies for 3 student startups. Believes great products start with great research.',
    'LOOKING_FOR_TEAM',
    ['User Research','Figma','Usability Testing','Data Analysis','Python','SQL'],['Figma','Python','SQL'],
    'tanyamishra_ux',6,71,12,1,
    [{name:'ResearchKit',desc:'Toolkit for running async usability studies with students.',tech:['React','Firebase','Python'],link:'#'}],
    'Bangalore, India',
    ['IIIT Bangalore Best Thesis Candidate','CHI 2025 Student Volunteer','Human Factors Society Member'],
    {github:'tanyamishra_ux',linkedin:'tanyamishra'},
    'IIIT Bangalore','Bangalore Urban','Bangalore','Karnataka',
    ['UX Research','Human-Computer Interaction','Design'],['Design','Research','EdTech']),

  mk(19,'Kabir Singh','Kabir','ffdfbf',
    'LNM Institute of Information Technology','3rd Year','Computer Science',
    'Open source contributor and community builder. Maintains 2 OSS tools with 1k+ GitHub stars. Looking to build with purpose.',
    'OPEN_TO_INVITES',
    ['Python','Django','PostgreSQL','GraphQL','Docker','Linux','Celery'],['Python','Django','PostgreSQL','Docker'],
    'kabirsingh_oss',38,934,1240,4,
    [{name:'OpenPR',desc:'OSS tool for automated PR review and CI reporting — 1.2k stars.',tech:['Python','Django','GitHub API'],link:'#'},
     {name:'TaskEngine',desc:'Distributed task queue on Celery with visual dashboard.',tech:['Python','Celery','Redis','React'],link:'#'}],
    'Jaipur, India',
    ['GitHub Arctic Code Vault Contributor','Google Season of Docs 2024','MLH Open Source Fellowship'],
    {github:'kabirsingh_oss',linkedin:'kabirsingh',twitter:'kabir_oss'},
    'LNMIIT','Jaipur','Jaipur','Rajasthan',
    ['Open Source','Community Building','Backend'],['Open Source','Developer Tools','Infrastructure']),

  mk(20,'Divya Nambiar','Divya','d1d4f9',
    'Kerala Technological University','4th Year','Computer Science',
    "AI product builder focused on EdTech. Formerly at BYJU's tech team. Building AI tutoring tools that truly adapt to each student.",
    'LOOKING_FOR_MEMBERS',
    ['Python','LangChain','React','FastAPI','Vector DBs','PostgreSQL','AWS'],['Python','LangChain','React','FastAPI'],
    'divyanambiar_ai',20,578,134,6,
    [{name:'TutorAI',desc:'Adaptive AI tutor using knowledge graphs + LLMs, 200+ users.',tech:['Python','LangChain','Neo4j','React'],link:'#'},
     {name:'QuizForge',desc:'Automatic quiz generation from any study material.',tech:['FastAPI','OpenAI','PostgreSQL'],link:'#'}],
    'Thiruvananthapuram, India',
    ["BYJU's Tech Intern 2024",'KTU Startup Innovation Award','Microsoft Imagine Cup Semi-finalist'],
    {github:'divyanambiar_ai',linkedin:'divyanambiar',twitter:'divya_builds_ai'},
    'KTU','Thiruvananthapuram','Thiruvananthapuram','Kerala',
    ['AI Products','EdTech','LLMs'],['EdTech','AI/ML','SaaS']),
]

export const hackathons = [
  { id:1, title:'AI for Good Hackathon 2026', organizer:'Google Developer Students', date:'2026-07-18', endDate:'2026-07-20', location:'Online + Hyderabad Hub', prize:'₹5,00,000', teamSize:'2–5', tracks:['Healthcare AI','Climate Tech','EdTech'], status:'upcoming', registered:1240, description:'Build AI-powered solutions for social good. Open to all college students across India.', tags:['AI','Social Impact','Google'], userRegistered:false },
  { id:2, title:'HackIndia 2026', organizer:'India Blockchain Week', date:'2026-08-03', endDate:'2026-08-04', location:'Bangalore + Online', prize:'₹10,00,000', teamSize:'2–4', tracks:['Web3','DeFi','NFT Infrastructure'], status:'upcoming', registered:3500, description:"India's largest Web3 hackathon. Build on Ethereum, Solana, or Polkadot.", tags:['Web3','Blockchain','DeFi'], userRegistered:true },
  { id:3, title:'SRM Hack 2026', organizer:'SRM Institute of Science and Technology', date:'2026-08-15', endDate:'2026-08-16', location:'SRM University, Chennai', prize:'₹1,50,000', teamSize:'2–4', tracks:['IoT','Smart Cities','HealthTech'], status:'upcoming', registered:680, description:'Inter-college hackathon focused on real-world engineering solutions.', tags:['IoT','Smart Cities','On-site'], userRegistered:false },
  { id:4, title:'MLH Global Hack Week', organizer:'Major League Hacking', date:'2026-09-01', endDate:'2026-09-07', location:'Online (Global)', prize:'Swag + Internships', teamSize:'1–4', tracks:['Open Source','Web','Mobile','AI/ML'], status:'upcoming', registered:12000, description:'Week-long global hacking event with daily challenges from top tech companies.', tags:['MLH','Global','Open Source'], userRegistered:false },
  { id:5, title:'Smart India Hackathon 2026', organizer:'Ministry of Education, India', date:'2026-09-20', endDate:'2026-09-22', location:'Pan India (Multiple Nodes)', prize:'₹1,00,000 per team', teamSize:'6', tracks:['Agriculture','HealthCare','Smart Automation','Education','Fintech'], status:'upcoming', registered:50000, description:"India's national hackathon connecting students with real government problem statements.", tags:['Government','National','High Prestige'], userRegistered:false },
]

export const projects = [
  { id:1, title:'AI Mental Health Companion', category:'research', description:'Research project building an LLM-based mental health support chatbot for college students.', tech:['Python','LangChain','FastAPI','React'], openRoles:['ML Engineer','Frontend Dev','Clinical Advisor'], team:[users[1]], university:'NIT Trichy', status:'recruiting', deadline:'2026-07-30' },
  { id:2, title:'CampusConnect — Student Networking App', category:'college', description:'Final-year capstone project. Building a LinkedIn-like platform for college students.', tech:['React','Node.js','PostgreSQL','Tailwind'], openRoles:['React Developer','UI/UX Designer'], team:[users[0],users[3]], university:'SKCET', status:'recruiting', deadline:'2026-08-15' },
  { id:3, title:'GreenChain — Carbon Credit DApp', category:'opensource', description:'Open source DApp for trading carbon credits on Ethereum. All skill levels welcome.', tech:['Solidity','React','Ethers.js','Hardhat'], openRoles:['Solidity Dev','React Dev','Technical Writer'], team:[users[7]], university:'Open Source', status:'active', deadline:null },
  { id:4, title:'EduOS — Learning Management System', category:'startup', description:'Pre-seed startup building the next-gen LMS for tier-2 colleges. Equity offered.', tech:['Next.js','PostgreSQL','Python','AI/ML'], openRoles:['CTO / Tech Lead','AI Engineer','Product Designer'], team:[users[19]], university:'Multi-university', status:'recruiting', deadline:'2026-08-01' },
  { id:5, title:'BCI Assistive Typing Research', category:'research', description:'Cross-university research building EEG-based assistive typing for motor-impaired individuals.', tech:['Python','MNE','TensorFlow','MATLAB'], openRoles:['ML Researcher','Signal Processing Engineer','Frontend Dev'], team:[users[13]], university:'Amrita Vishwa Vidyapeetham', status:'recruiting', deadline:'2026-09-01' },
]

export const myTeam = {
  id:1, name:'Team Nexus', hackathon:'HackIndia 2026',
  description:'Building a decentralized credential verification platform for college students using zero-knowledge proofs.',
  members:[{...users[0],role:'Team Lead & Backend'},{...users[2],role:'UI/UX Designer'}],
  missingRoles:['Blockchain / Solidity Developer','Frontend React Developer','Product Manager'],
  createdAt:'2026-06-20', status:'recruiting',
  healthScores:{ Frontend:40, Backend:80, 'AI/ML':20, Design:90, Product:50 },
}

export const notifications = [
  { id:1, type:'invite', from:users[3], message:'Karan Mehta invited you to join Team Nexus for HackIndia 2026.', action:'view_invite', time:'2 hours ago', read:false },
  { id:2, type:'match',  message:'You have 3 new AI-matched builders for your HackIndia team.', action:'view_matches', time:'5 hours ago', read:false },
  { id:3, type:'update', from:users[1], message:'Riya Nair accepted your connection request.', action:null, time:'1 day ago', read:true },
  { id:4, type:'hackathon', message:"HackIndia 2026 registration closes in 3 days. You're registered!", action:'view_hackathon', time:'1 day ago', read:true },
  { id:5, type:'system', message:'Your GitHub profile was successfully connected. 24 repos imported.', action:null, time:'3 days ago', read:true },
  { id:6, type:'invite', from:users[6], message:'Sneha Krishnamurthy invited you to collaborate on BharatLLM.', action:'view_invite', time:'4 days ago', read:true },
]

export const recommendations = [
  { id:1, builder:users[1], reason:"Riya is a strong fit because your team has no ML engineer and she has shipped 3 AI/ML projects in the last 6 months, including MediPredict which was recognized at Smart India Hackathon. Her FastAPI experience also fills your API development gap.", fitAreas:['AI/ML','Backend'], hackathon:'HackIndia 2026' },
  { id:2, builder:users[2], reason:"Priya fills your critical design gap. Your team has strong backend coverage but no dedicated designer — she has shipped a production design system used by 500+ students and actively contributes to open source Figma resources.", fitAreas:['Design','Frontend'], hackathon:'HackIndia 2026' },
  { id:3, builder:users[7], reason:"Rohan brings Solidity and Web3 skills your team is missing. He has audited 5 smart contracts and won ETHIndia 2024 — directly relevant to building a decentralized credential verification platform.", fitAreas:['Blockchain','Web3'], hackathon:'HackIndia 2026' },
  { id:4, builder:users[16], reason:"Ishaan fills your frontend gap with production-grade React expertise. He has shipped a component library used across 10+ projects and his AnimateX package has 3k weekly npm downloads — your product's UX would immediately benefit.", fitAreas:['Frontend','UI'], hackathon:'HackIndia 2026' },
]

export const currentUser = { ...users[0], status: 'LOOKING_FOR_TEAM' }
