"""add_project_applications

Revision ID: 4a04239898b2
Revises: c1b3ee3c7198
Create Date: 2026-07-12 17:09:16.040977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a04239898b2'
down_revision: Union[str, Sequence[str], None] = 'c1b3ee3c7198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    try:
        op.execute("ALTER TYPE notificationtype ADD VALUE 'invite_declined'")
    except Exception:
        pass
    op.create_table('project_applications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_project_application')
    )
    op.create_index(op.f('ix_project_applications_project_id'), 'project_applications', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_applications_user_id'), 'project_applications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_applications_user_id'), table_name='project_applications')
    op.drop_index(op.f('ix_project_applications_project_id'), table_name='project_applications')
    op.drop_table('project_applications')
    # ### end Alembic commands ###
