"""add_ai_usage_and_cache_tables

Revision ID: 6938659ff7d0
Revises: a3b8c4d2e1f5
Create Date: 2026-07-18 00:34:51.836539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6938659ff7d0'
down_revision: Union[str, Sequence[str], None] = 'a3b8c4d2e1f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_caches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=256), nullable=False),
    sa.Column('feature_name', sa.String(length=50), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key', name='uq_cache_key')
    )
    op.create_index(op.f('ix_ai_caches_cache_key'), 'ai_caches', ['cache_key'], unique=True)
    op.create_table('ai_usages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('feature_name', sa.String(length=50), nullable=False),
    sa.Column('usage_date', sa.Date(), nullable=False),
    sa.Column('request_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'feature_name', 'usage_date', name='uq_user_feature_date')
    )
    op.create_index(op.f('ix_ai_usages_user_id'), 'ai_usages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ai_usages_user_id'), table_name='ai_usages')
    op.drop_table('ai_usages')
    op.drop_index(op.f('ix_ai_caches_cache_key'), table_name='ai_caches')
    op.drop_table('ai_caches')
    # ### end Alembic commands ###
